---
deployment:
    tasks:
      - export DEPLOYPATH=/home/ericbhtn/apps/web-app-erick
      - /bin/cp -r static/ $DEPLOYPATH
      - /bin/cp -r templates/ $DEPLOYPATH
      - /bin/cp main.py $DEPLOYPATH
